import pandas as pd
import os
import shutil
import re

def sanitize_filename(name):
    return re.sub(r'[<>:"/\\|?*]', '', str(name)).replace(' ', '_')

def organize_files():
    csv_path = '/workspaces/DSA-prep/notes/spreadsheet_data.csv'
    notes_dir = '/workspaces/DSA-prep/notes'
    
    # Read CSV
    df = pd.read_csv(csv_path, header=1)
    
    # Rename columns for clarity (same as download script)
    df = df.rename(columns={
        df.columns[0]: 'Date',
        df.columns[1]: 'Topic',
        'Digital Notes': 'Digital_Link',
        'Handwritten Notes': 'Handwritten_Link'
    })

    for index, row in df.iterrows():
        topic_name = str(row['Topic']).strip()
        if not topic_name or topic_name.lower() == 'nan':
            continue

        sanitized_topic = sanitize_filename(topic_name)
        topic_dir = os.path.join(notes_dir, sanitized_topic)
        
        # Create topic directory if it doesn't exist
        if not os.path.exists(topic_dir):
            os.makedirs(topic_dir)
            print(f"Created directory: {topic_dir}")

        date = str(row['Date']).replace('/', '-')
        
        # Expected filenames
        filenames = [
            f"{date}_{sanitized_topic}_Digital.pdf",
            f"{date}_{sanitized_topic}_Handwritten.pdf"
        ]
        
        for filename in filenames:
            src_path = os.path.join(notes_dir, filename)
            dst_path = os.path.join(topic_dir, filename)
            
            if os.path.exists(src_path):
                print(f"Moving {filename} to {sanitized_topic}/")
                shutil.move(src_path, dst_path)
            elif os.path.exists(dst_path):
                 print(f"{filename} already in {sanitized_topic}/")
            else:
                # Handle potential newline issues in filenames generated by previous script?
                # The previous script used:
                # topic = sanitize_filename(row['Topic'])
                # output_filename = f"{date}_{topic}_{note_type}.pdf"
                # So the filenames should match unless sanitize_filename behaves differently.
                pass

if __name__ == "__main__":
    organize_files()
